heat_template_version: queens

description: >
  Software Config to drive os-net-config with 2 bonded nics on a bridge
  with VLANs attached for the controller role.

parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal API network
    type: string
  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage mgmt network
    type: string
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  ManagementIpSubnet: # Only populated when including environments/network-management.yaml
    default: ''
    description: IP address/subnet on the management network
    type: string
  LinuxBondInterfaceOptions:
    default: ''
    description: The ovs_options string for the bond interface. Set things like
                 lacp=active and/or bond_mode=balance-slb using this option.
    type: string 
  DpdkBondInterfaceOvsOptions:
    default: ''
    description: 
    type: string
  ExternalNetworkVlanID:
    default: 100
    description: Vlan ID for the external network traffic.
    type: number
  InternalApiNetworkVlanID:
    default: 1020
    description: Vlan ID for the internal_api network traffic.
    type: number
  StorageNetworkVlanID:
    default: 1030
    description: Vlan ID for the storage network traffic.
    type: number
  StorageMgmtNetworkVlanID:
    default: 1040
    description: Vlan ID for the storage mgmt network traffic.
    type: number
  TenantNetworkVlanID:
    default: 1060
    description: Vlan ID for the tenant network traffic.
    type: number
  ManagementNetworkVlanID:
    default: 60
    description: Vlan ID for the management network traffic.
    type: number
  ExternalInterfaceDefaultRoute:
    default: ''
    description: default route for the external network
    type: string
  ControlPlaneDefaultRoute: # Override this via parameter_defaults
    description: The default route of the control plane network.
    type: string
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  DnsServers: # Override this via parameter_defaults
    default: []
    description: A list of DNS servers (2 max for some implementations) that will be added to resolv.conf.
    type: comma_delimited_list
  EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string

resources:
  OsNetConfigImpl:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template:
            get_file: /usr/share/openstack-tripleo-heat-templates/network/scripts/run-os-net-config.sh
          params:
            $network_config:
              network_config:
              - type: interface
                name: ens255f1 
                use_dhcp: false
                addresses:
                 -
                  ip_netmask:
                    list_join:
                      - /
                      - - get_param: ControlPlaneIp
                        - get_param: ControlPlaneSubnetCidr
                routes:
                 -
                  ip_netmask: 169.254.169.254/32
                  next_hop: 
                    get_param: EC2MetadataIp
                 -
                  default: true
                  next_hop: 
                    get_param: ControlPlaneDefaultRoute

              - 
                type: interface
                name: ens255f0
                use_dhcp: false
                defroute: false

              -
                type: interface
                name: ens6f0
                use_dhcp: false
                defroute: false

              -
                type: linux_bond
                name: bond1
                bonding_options: "mode=active-backup"
                use_dhcp: false
                dns_servers:
                   get_param: DnsServers
                members:
                   -
                      type: interface
                      name: ens3f0
                      primary: true
              -
                type: vlan
                device: bond1
                vlan_id: 
                    get_param: InternalApiNetworkVlanID
                addresses:
                -
                  ip_netmask: 
                    get_param: InternalApiIpSubnet
              -
                type: vlan
                device: bond1
                vlan_id: 
                    get_param: StorageNetworkVlanID
                addresses:
                -
                  ip_netmask: 
                    get_param: StorageIpSubnet
              -
                type: vlan
                device: bond1
                vlan_id: 
                    get_param: StorageMgmtNetworkVlanID
                addresses:
                -
                  ip_netmask: 
                    get_param: StorageMgmtIpSubnet
              -
                type: ovs_user_bridge
                name: br-dpdk1
                use_dhcp: false
                members:
                ovs_extra:
                 -
                  str_replace:
                    template: set port br-Haresh_dpdk1 tag=_VLAN_TAG_
                    params:
                      _VLAN_TAG_: 
                         get_param: TenantNetworkVlanID
                addresses:
                  -
                    ip_netmask: 
                      get_param: TenantIpSubnet
                members:
                  -
                    type: ovs_dpdk_bond
                    name: dpdkbond0
                   # ovs_options: 
                   #    get_param: DpdkBondInterfaceOvsOptions
                    members:
                      -
                        type: ovs_dpdk_port
                        name: dpdk0
                        members:
                          -
                            type: interface
                            name: ens3f1
                      -
                        type: ovs_dpdk_port
                        name: dpdk1
                        members:
                          -
                            type: interface
                            name: ens6f1

outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value: 
      get_resource: OsNetConfigImpl
